#!/bin/bash

# Call this command as root on your server to install check-edge:
# sudo curl -s https://raw.githubusercontent.com/befranz/check-edge/master/install-check-edge|bash&&source $HOME/.profile

VERSION="1.0"
WHOAMI=$(whoami)
SPATH="$HOME/scripts"
SCRIPT="$SPATH/check-edge"
GIT="https://raw.githubusercontent.com/befranz/check-edge/master/check-edge"
JOB="*/10 * * * * $SCRIPT >/dev/null 2>&1"
TMPC="/tmp/check-edge-cron"

if [ "$WHOAMI" = "root" ]; then
    mkdir -p "$SPATH"
    CURLRC=$(curl -s -w '%{http_code}' "$GIT" -o "$SCRIPT")
    if [ "$CURLRC" = "200" ]; then
      chmod +x "$SCRIPT"
      cp -n "$HOME/.profile" "$HOME/.profile.bak"
      grep -q "$SPATH" "$HOME/.profile" || echo "export PATH=\$PATH:$SPATH" >> "$HOME/.profile"
      grep "$SCRIPT" -q <(crontab -l) || (crontab -l>"$TMPC"; echo "$JOB">>"$TMPC"; crontab "$TMPC")
      rm -f "$TMPC"
      echo
      echo 'Installation of check-edge successful! Just type "check-edge" to start it manually.'
      echo 'A Cron Job exists to run check-edge every 10 minutes. You can check this by "crontab -l".'
      echo
      exit 0
    else
      echo
      echo "Something went wrong with the installation!"
      echo
      exit 1
    fi
else
    echo
    echo "Only user root can run check-edge! Installation failed."
    echo
    exit 1
fi
